"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ProductShell } from "@/components/product-shell/ProductShell";
import { HologramEarth } from "@/components/hologram-earth/HologramEarth";
import { Icon } from "@/components/product-shell/Icon";
import { haptic } from "@/lib/haptics";
import styles from "./settings.module.css";

type Section="profile"|"privacy"|"appearance"|"sessions";
type S={id:string;deviceLabel:string;deviceType:string;timezone:string|null;latitude:number|null;longitude:number|null;locationMode:string|null;lastSeenAt:string;revokedAt:string|null;current:boolean};
async function json<T>(r:Response):Promise<T|null>{const t=await r.text();try{return t?JSON.parse(t) as T:null}catch{return null}}
export default function SettingsPage(){
 const router=useRouter();const[section,setSection]=useState<Section>("profile"),[haptics,setHaptics]=useState(true),[light,setLight]=useState(false),[receipts,setReceipts]=useState(true),[seen,setSeen]=useState(false),[requests,setRequests]=useState(true),[sessions,setSessions]=useState<S[]>([]),[currentId,setCurrentId]=useState<string|null>(null),[error,setError]=useState<string|null>(null);
 const current=useMemo(()=>sessions.find(x=>x.id===currentId||x.current)??null,[sessions,currentId]);
 const load=useCallback(async()=>{const r=await fetch("/api/sessions",{cache:"no-store"});const d=await json<{sessions?:S[];currentSessionId?:string|null;error?:string}>(r);if(!r.ok)setError(d?.error??"Unable to load sessions.");else{setSessions(d?.sessions??[]);setCurrentId(d?.currentSessionId??null)}},[]);
 useEffect(()=>{setHaptics(localStorage.getItem("ipchat-haptics")!=="off");setLight(localStorage.getItem("ipchat-theme")==="light");if(section==="sessions")void load()},[section,load]);
 function choose(x:Section){haptic();setSection(x)}
 function theme(){haptic("light");const n=!light;setLight(n);localStorage.setItem("ipchat-theme",n?"light":"dark");document.documentElement.dataset.ipTheme=n?"light":"dark"}
 function hapticToggle(){const n=!haptics;setHaptics(n);localStorage.setItem("ipchat-haptics",n?"on":"off");if(n)haptic("success")}
 function locate(mode:"approximate"|"precise"){haptic("medium");if(!navigator.geolocation){setError("Location is not supported.");return}navigator.geolocation.getCurrentPosition(async p=>{const latitude=mode==="approximate"?Number(p.coords.latitude.toFixed(2)):p.coords.latitude;const longitude=mode==="approximate"?Number(p.coords.longitude.toFixed(2)):p.coords.longitude;const r=await fetch("/api/sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({locationMode:mode,latitude,longitude,accuracy:p.coords.accuracy,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,language:navigator.language})});if(!r.ok)setError((await json<{error?:string}>(r))?.error??"Unable to save location.");else haptic("success");await load()},()=>setError("Location permission was denied."),{enableHighAccuracy:mode==="precise",timeout:12000})}
 async function clearLocation(){haptic();await fetch("/api/sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({locationMode:"off",latitude:null,longitude:null,accuracy:null})});await load()}
 async function revoke(id:string){haptic("warning");const r=await fetch(`/api/sessions/${id}`,{method:"DELETE"});const d=await json<{current?:boolean;error?:string}>(r);if(!r.ok){setError(d?.error??"Unable to revoke session.");return}if(d?.current){router.push("/login");router.refresh()}else await load()}
 const menu=[['profile','user','Profile','Identity and account'],['privacy','shield','Privacy','Visibility and requests'],['appearance','palette','Appearance','Theme and haptics'],['sessions','devices','Sessions','Devices and location']] as const;
 return <ProductShell title="Settings"><div className={styles.page}><section className={styles.hero}><div><small>CONTROL CENTER</small><h1>Important settings.<br/>Nothing extra.</h1><p>Profile, privacy, appearance, haptics, devices and location are consolidated into one premium screen.</p></div><div className={styles.orb}><Icon name="settings" size={35}/><i/><i/></div></section><div className={styles.layout}><aside className={styles.menu}><div className={styles.user}><span>YP</span><div><strong>Your account</strong><small>@your_account</small></div></div>{menu.map(([id,icon,title,copy])=><button key={id} className={section===id?styles.active:""} onClick={()=>choose(id)}><i><Icon name={icon}/></i><span><strong>{title}</strong><small>{copy}</small></span><Icon name="arrow" size={14}/></button>)}</aside><section className={styles.panel}>
 {section==="profile"&&<div className={styles.section}><Header k="IDENTITY" title="Your profile" copy="Only the public identity you choose is visible to other people."/><div className={styles.profile}><span>YP</span><div><strong>Your account</strong><small>@your_account</small><p>Private messenger · Ahmedabad</p></div><button onClick={()=>haptic("light")}><Icon name="edit"/>Edit</button></div><div className={styles.cards}><article><Icon name="lock"/><strong>Phone hidden</strong><small>Used for verification, not public discovery.</small></article><article><Icon name="qr"/><strong>Private QR</strong><small>Connect without revealing your number.</small></article></div></div>}
 {section==="privacy"&&<div className={styles.section}><Header k="PRIVACY" title="You decide what is visible" copy="Clear controls with no hidden tracking behavior."/><div className={styles.toggles}><Toggle icon="eye" title="Read receipts" copy="Show when messages are read." value={receipts} onClick={()=>{haptic();setReceipts(x=>!x)}}/><Toggle icon="history" title="Last seen" copy="Show recent activity to contacts." value={seen} onClick={()=>{haptic();setSeen(x=>!x)}}/><Toggle icon="message" title="Message requests" copy="Allow new people to request a chat." value={requests} onClick={()=>{haptic();setRequests(x=>!x)}}/></div><div className={styles.note}><Icon name="shield"/><span><strong>Phone numbers stay private</strong><small>People connect by username, QR or invite.</small></span></div></div>}
 {section==="appearance"&&<div className={styles.section}><Header k="EXPERIENCE" title="Premium motion and feel" copy="Theme, animation and haptic behavior apply across the four core sections."/><div className={styles.themes}><button className={light?styles.selected:""} onClick={theme}><i className={styles.lightPreview}/><strong>Light</strong><small>Clean and bright</small></button><button className={!light?styles.selected:""} onClick={theme}><i className={styles.darkPreview}/><strong>Midnight</strong><small>Neon glass depth</small></button></div><div className={styles.haptic}><i><Icon name="sparkles"/></i><span><strong>Haptic feedback</strong><small>Subtle vibration on supported Android browsers.</small></span><button className={haptics?styles.on:""} onClick={hapticToggle}><b/></button></div><div className={styles.note}><Icon name="accessibility"/><span><strong>Reduce motion supported</strong><small>System accessibility preference is respected.</small></span></div></div>}
 {section==="sessions"&&<div className={styles.section}><Header k="SESSION RADAR" title="Devices and location" copy="The hologram Earth shows only location you explicitly allow."/><div className={styles.sessionHero}><HologramEarth compact interactive showTelemetry latitude={current?.latitude??null} longitude={current?.longitude??null} label={current?.locationMode&&current.locationMode!=="off"?"CURRENT SESSION LOCATED":"LOCATION LAYER PRIVATE"}/><div><span><small>ACTIVE</small><strong>{sessions.filter(x=>!x.revokedAt).length}</strong></span><span><small>LOCATION</small><strong>{current?.locationMode??"off"}</strong></span><span><small>DEVICE</small><strong>{current?.deviceType??"—"}</strong></span></div></div><div className={styles.location}><button onClick={()=>locate("approximate")}><Icon name="globe"/>Approximate</button><button onClick={()=>locate("precise")}><Icon name="settings"/>Precise</button><button onClick={()=>void clearLocation()}><Icon name="block"/>Off</button></div>{error&&<p className={styles.error}>{error}</p>}<div className={styles.sessions}>{sessions.map(s=><article key={s.id}><i><Icon name={s.deviceType==="Mobile"?"phone":"devices"}/></i><span><strong>{s.deviceLabel}{s.current?" · Current":""}</strong><small>{s.timezone??"Timezone not synced"} · {new Date(s.lastSeenAt).toLocaleDateString()}</small></span>{!s.revokedAt&&<button onClick={()=>void revoke(s.id)}>{s.current?"Sign out":"Revoke"}</button>}</article>)}</div></div>}
 </section></div></div></ProductShell>
}
function Header({k,title,copy}:{k:string;title:string;copy:string}){return <header><small>{k}</small><h2>{title}</h2><p>{copy}</p></header>}
function Toggle({icon,title,copy,value,onClick}:{icon:string;title:string;copy:string;value:boolean;onClick:()=>void}){return <button onClick={onClick}><i><Icon name={icon}/></i><span><strong>{title}</strong><small>{copy}</small></span><b className={value?styles.switchOn:""}><em/></b></button>}
