"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { ProductShell } from "@/components/product-shell/ProductShell";
import { HologramEarth } from "@/components/hologram-earth/HologramEarth";
import { Icon } from "@/components/product-shell/Icon";
import { haptic } from "@/lib/haptics";
import styles from "./settings.module.css";
type Section="profile"|"privacy"|"appearance"|"sessions";type S={id:string;deviceLabel:string;deviceType:string;timezone:string|null;latitude:number|null;longitude:number|null;locationMode:string|null;lastSeenAt:string;revokedAt:string|null;current:boolean};type Profile={username:string;displayName:string;bio:string|null};type Prefs={readReceipts:boolean;showLastSeen:boolean;allowMessageRequests:boolean};
async function j<T>(r:Response):Promise<T|null>{const t=await r.text();try{return t?JSON.parse(t) as T:null}catch{return null}}
export default function SettingsPage(){const router=useRouter();const[section,setSection]=useState<Section>("profile"),[haptics,setHaptics]=useState(true),[light,setLight]=useState(false),[prefs,setPrefs]=useState<Prefs>({readReceipts:true,showLastSeen:false,allowMessageRequests:true}),[profile,setProfile]=useState<Profile>({username:"account",displayName:"Your account",bio:null}),[edit,setEdit]=useState(false),[name,setName]=useState(""),[bio,setBio]=useState(""),[sessions,setSessions]=useState<S[]>([]),[currentId,setCurrentId]=useState<string|null>(null),[error,setError]=useState<string|null>(null);const current=useMemo(()=>sessions.find(x=>x.id===currentId||x.current)??null,[sessions,currentId]);
const loadSessions=useCallback(async()=>{const r=await fetch("/api/sessions",{cache:"no-store"});const d=await j<{sessions?:S[];currentSessionId?:string|null;error?:string}>(r);if(!r.ok)setError(d?.error??"Unable to load sessions.");else{setSessions(d?.sessions??[]);setCurrentId(d?.currentSessionId??null)}},[]);
useEffect(()=>{setHaptics(localStorage.getItem("ipchat-haptics")!=="off");setLight(localStorage.getItem("ipchat-theme")==="light");void fetch("/api/profile").then(async r=>{const d=await j<{profile?:Profile}>(r);if(d?.profile){setProfile(d.profile);setName(d.profile.displayName);setBio(d.profile.bio??"")}});void fetch("/api/preferences").then(async r=>{const d=await j<{preferences?:Prefs}>(r);if(d?.preferences)setPrefs(d.preferences)});},[]);useEffect(()=>{if(section==="sessions")void loadSessions()},[section,loadSessions]);
function choose(x:Section){haptic();setError(null);setSection(x)}function theme(){haptic("light");const n=!light;setLight(n);localStorage.setItem("ipchat-theme",n?"light":"dark");document.documentElement.dataset.ipTheme=n?"light":"dark"}function hapticToggle(){const n=!haptics;setHaptics(n);localStorage.setItem("ipchat-haptics",n?"on":"off");if(n)haptic("success")}
async function savePref(key:keyof Prefs,value:boolean){haptic();const next={...prefs,[key]:value};setPrefs(next);const r=await fetch("/api/preferences",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({[key]:value})});if(!r.ok)setError("Preference could not be saved.")}
async function saveProfile(){const r=await fetch("/api/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({displayName:name,bio})});const d=await j<{profile?:Profile;error?:string}>(r);if(!r.ok||!d?.profile){setError(d?.error??"Profile could not be saved.");return}setProfile(d.profile);setEdit(false);haptic("success")}
function locate(mode:"approximate"|"precise"){haptic("medium");if(!navigator.geolocation){setError("Location is not supported.");return}navigator.geolocation.getCurrentPosition(async p=>{const latitude=mode==="approximate"?Number(p.coords.latitude.toFixed(2)):p.coords.latitude;const longitude=mode==="approximate"?Number(p.coords.longitude.toFixed(2)):p.coords.longitude;const r=await fetch("/api/sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({locationMode:mode,latitude,longitude,accuracy:p.coords.accuracy,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,language:navigator.language})});if(!r.ok)setError((await j<{error?:string}>(r))?.error??"Unable to save location.");else haptic("success");await loadSessions()},()=>setError("Location permission was denied."),{enableHighAccuracy:mode==="precise",timeout:12000})}
async function clearLocation(){await fetch("/api/sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({locationMode:"off",latitude:null,longitude:null,accuracy:null})});await loadSessions()}async function revoke(id:string){const r=await fetch(`/api/sessions/${id}`,{method:"DELETE"});const d=await j<{current?:boolean;error?:string}>(r);if(!r.ok){setError(d?.error??"Unable to revoke session.");return}if(d?.current){router.push("/login");router.refresh()}else await loadSessions()}
const menu=[["profile","user","Profile","Identity and account"],["privacy","shield","Privacy","Saved preferences"],["appearance","palette","Appearance","Theme and haptics"],["sessions","devices","Sessions","Devices and location"]] as const;return <ProductShell title="Settings"><div className={styles.page}><section className={styles.hero}><div><small>CONTROL CENTER</small><h1>Important settings.<br/>Nothing extra.</h1><p>Profile, privacy, appearance, haptics, devices and location are consolidated into one premium screen.</p></div><div className={styles.orb}><Icon name="settings" size={35}/><i/><i/></div></section><div className={styles.layout}><aside className={styles.menu}><div className={styles.user}><span>{profile.displayName.slice(0,2).toUpperCase()}</span><div><strong>{profile.displayName}</strong><small>@{profile.username}</small></div></div>{menu.map(([id,icon,title,copy])=><button key={id} className={section===id?styles.active:""} onClick={()=>choose(id)}><i><Icon name={icon}/></i><span><strong>{title}</strong><small>{copy}</small></span><Icon name="arrow" size={14}/></button>)}</aside><section className={styles.panel}>
{error&&<p className={styles.error}>{error}</p>}
{section==="profile"&&<div className={styles.section}><Header k="IDENTITY" title="Your profile" copy="Edit your real public identity. Changes are saved to your account."/><div className={styles.profile}><span>{profile.displayName.slice(0,2).toUpperCase()}</span><div><strong>{profile.displayName}</strong><small>@{profile.username}</small><p>{profile.bio||"No bio yet."}</p></div><button onClick={()=>setEdit(true)}><Icon name="edit"/>Edit</button></div>{edit&&<div className={styles.editor}><label>Display name<input value={name} onChange={e=>setName(e.target.value.slice(0,50))}/></label><label>Bio<textarea value={bio} onChange={e=>setBio(e.target.value.slice(0,160))}/></label><div><button onClick={()=>setEdit(false)}>Cancel</button><button onClick={()=>void saveProfile()}>Save profile</button></div></div>}<div className={styles.cards}><article><Icon name="lock"/><strong>Phone hidden</strong><small>Used for verification, not public discovery.</small></article><article><Icon name="qr"/><strong>Username identity</strong><small>Connect without revealing your number.</small></article></div></div>}
{section==="privacy"&&<div className={styles.section}><Header k="PRIVACY" title="Saved privacy controls" copy="These choices are stored in Neon and remain after refresh or sign-in."/><div className={styles.toggles}><Toggle icon="eye" title="Read receipts" copy="Show when messages are read." value={prefs.readReceipts} onClick={()=>void savePref("readReceipts",!prefs.readReceipts)}/><Toggle icon="history" title="Last seen" copy="Show recent activity to contacts." value={prefs.showLastSeen} onClick={()=>void savePref("showLastSeen",!prefs.showLastSeen)}/><Toggle icon="message" title="Message requests" copy="Allow new people to request a chat." value={prefs.allowMessageRequests} onClick={()=>void savePref("allowMessageRequests",!prefs.allowMessageRequests)}/></div></div>}
{section==="appearance"&&<div className={styles.section}><Header k="EXPERIENCE" title="Premium motion and feel" copy="Theme and haptic behavior apply across the four core sections."/><div className={styles.themes}><button className={light?styles.selected:""} onClick={theme}><i className={styles.lightPreview}/><strong>Light</strong><small>Clean and bright</small></button><button className={!light?styles.selected:""} onClick={theme}><i className={styles.darkPreview}/><strong>Midnight</strong><small>Neon glass depth</small></button></div><div className={styles.haptic}><i><Icon name="sparkles"/></i><span><strong>Haptic feedback</strong><small>Subtle vibration on supported Android browsers.</small></span><button className={haptics?styles.on:""} onClick={hapticToggle}><b/></button></div></div>}
{section==="sessions"&&<div className={styles.section}><Header k="SESSION RADAR" title="Devices and location" copy="Legacy logins upgrade automatically. Revoked sessions are blocked in middleware and APIs."/><div className={styles.sessionHero}><HologramEarth compact interactive showTelemetry latitude={current?.latitude??null} longitude={current?.longitude??null} label={current?.locationMode&&current.locationMode!=="off"?"CURRENT SESSION LOCATED":"LOCATION LAYER PRIVATE"}/><div><span><small>ACTIVE</small><strong>{sessions.filter(x=>!x.revokedAt).length}</strong></span><span><small>LOCATION</small><strong>{current?.locationMode??"off"}</strong></span><span><small>DEVICE</small><strong>{current?.deviceType??"—"}</strong></span></div></div><div className={styles.location}><button onClick={()=>locate("approximate")}><Icon name="globe"/>Approximate</button><button onClick={()=>locate("precise")}><Icon name="settings"/>Precise</button><button onClick={()=>void clearLocation()}><Icon name="block"/>Off</button></div><div className={styles.sessions}>{sessions.map(s=><article key={s.id}><i><Icon name={s.deviceType==="Mobile"?"phone":"devices"}/></i><span><strong>{s.deviceLabel}{s.current?" · Current":""}</strong><small>{s.timezone??"Timezone not synced"} · {new Date(s.lastSeenAt).toLocaleDateString()}</small></span>{!s.revokedAt&&<button onClick={()=>void revoke(s.id)}>{s.current?"Sign out":"Revoke"}</button>}</article>)}</div></div>}
</section></div></div></ProductShell>}
function Header({k,title,copy}:{k:string;title:string;copy:string}){return <header><small>{k}</small><h2>{title}</h2><p>{copy}</p></header>}function Toggle({icon,title,copy,value,onClick}:{icon:string;title:string;copy:string;value:boolean;onClick:()=>void}){return <button onClick={onClick}><i><Icon name={icon}/></i><span><strong>{title}</strong><small>{copy}</small></span><b className={value?styles.switchOn:""}><em/></b></button>}
